version: "3.8"

services:
    url_shortner_api:
        build: .
        ports:
            - 80:80
        environment:
            - MONGO_URI=mongodb://url_shortner_db/urlShortner
            - ENV=dev
            - PYTHONPATH=./app
            - JWT_SECRET_KEY=my-32-character-ultra-secure-and-ultra-long-secret
        volumes:
            - ./app:/app
    url_shortner_db:
            image: mongo
            ports:
                - 27017:27017
            volumes:
            - localdb:/data/db
volumes:
    localdb: